spring:
  kafka:
    bootstrap-servers: https://pkc-kngm02.us-west-2.aws.confluent.cloud:9092
    consumer:
      group-id: demo-consumer-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
